import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Blog posts. Legacy Wix posts are JSON files generated by scripts/convert-posts.py
// (do not hand-edit those; edit the harvested source or the script and re-run).
// New posts can be added as JSON files with the same shape.
const posts = defineCollection({
  loader: glob({ pattern: '*.json', base: './src/content/posts' }),
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    description: z.string().default(''),
    published: z.string(),
    updated: z.string().optional(),
    author: z.string().default('Focus Accountancy'),
    topics: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    image: z.string().nullable().optional(),
    imageInline: z.boolean().default(false),
    words: z.number().optional(),
    legacy: z.boolean().default(false),
    html: z.string(),
  }),
});

// News items migrated from news.focusaccountancy.co.uk (syndicated newsfeed), via scripts/convert-news.py.
const news = defineCollection({
  loader: glob({ pattern: '*.json', base: './src/content/news' }),
  schema: z.object({
    slug: z.string(),
    id: z.number(),
    title: z.string(),
    summary: z.string().default(''),
    published: z.string(),
    image: z.string().nullable().optional(),
    words: z.number().optional(),
    html: z.string(),
  }),
});

export const collections = { posts, news };
